version: '3'
services:
  firmware:
    build: ./.devcontainer/firmware-container
    volumes:
      - .:/workspace:cached
    devices:
      - /dev/ttyACM0
    command: sleep infinity
  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
